### ISSUE TITLE
heroku-20 stack build error

### ISSUE THREAD

**Issue by jhnbkr** [grauwoelfchen/heroku-buildpack-gettext#1]
I have been using this buildpack for quite sometime now. I recently started a new project and it used the new stack `heroku-20` by default.

During deployment I get the following errors:
```
Execution of msgfmt failed: msgfmt: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory        
CommandError: compilemessages generated one or more errors.
```

edit: FYI I am using Django and exciting `python manage.py compilemessages` during release

**Comment by jhnbkr** [comment]
Based on the stack packages documentation it would appear libncurses5 was replaced with libncurses6. I am not very familiar with either so I cannot say this is the issue.

https://devcenter.heroku.com/articles/stack-packages

**Comment by jhnbkr** [comment]
I have discovered updating gettext to the latest (0.21) resolves this issue.

PR: https://github.com/grauwoelfchen/heroku-buildpack-gettext/pull/2

**Comment by jhnbkr** [comment]
https://github.com/grauwoelfchen/heroku-buildpack-gettext/pull/2

**Comment by grauwoelfchen** [comment]
@jhnbkr Thank you so much for using this! I've just merged your pull request :+1:

**Comment by grauwoelfchen** [comment]
Please feel free to reopen this if you have any problem relates to it. Good luck with your new project!
